@hostname = 127.0.0.1
@port = 8000
@serviceUrl = http://{{hostname}}:{{port}}
@baseUrl = http://{{hostname}}:{{port}}
###
GET {{baseUrl}}/

###
GET {{baseUrl}}/user
###

POST {{baseUrl}}/user/3
Content-Type: application/json

{
    "fname": "Yoongi",
    "lname": "Min",
    "username" : "M.yoongi",
    "email": "min.yunggi@example.com",
    "password" : "My19920309",
    "phone": "0984532763",
    "address": "123 Main St, Cityville"
}
###
POST {{baseUrl}}user/1/profile-image
Content-Type: application/json

{

}
###

PUT {{baseUrl}}/user/6
Content-Type: application/json

{
    "fname": "Taehyung",
    "lname": "Kim",
    "username" : "K.taehyung",
    "email": "kim.taehyung@example.com",
    "password" : "kt1995",
    "phone": "0873489327",
    "address": "123 Main St, Cityville",
    "roles" : "user"
}
###

DELETE {{baseUrl}}/user/12

###
GET {{baseUrl}}/admin
###
POST {{baseUrl}}/admin
Content-Type: application/json

{
   "fname": "Namjoon",
    "lname": "Kim",
    "username" : "K.RM",
    "email": "kim.namjoon@example.com",
    "password" : "nj1994",
    "phone": "0981218763",
    "address": "123 Main St, Cityville"

}

###
PUT {{baseUrl}}/admin/3
Content-Type: application/json

{
    "fname": "Jungkook",
    "lname": "Jeon",
    "username" : "J.jungkook",
    "email": "jeon.jungkook@example.com",
    "password" : "jj1997",
    "phone": "0871236327",
    "address": "123 Main St, Cityville",
    
}
###
DELETE {{baseUrl}}/admin/
###
GET {{baseUrl}}/post
###

POST {{baseUrl}}/post
Content-Type: application/json

{
    "content": "Agus D"
}
###
PUT {{baseUrl}}/post/3
Content-Type: application/json

{
    "content": "เชี่ย อคคตสึ ยูตะหร่อชิบหาย"
}
###
DELETE {{baseUrl}}/post/58
###

GET {{baseUrl}}/post/2/comment
###
POST {{baseUrl}}/post/11/comment
Content-Type: application/json

{
    "content":"จริงคั้บ"
}
###
PUT {{baseUrl}}/post/1/comment/2
Content-Type: application/json

{
    "content":"อคคตสึ ยูตะหร่อมากค่ะ"
}
###
DELETE {{baseUrl}}/post/1/comment/11
###

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "usernameOrEmail" : "min.yunggi@example.com",
    "password" : "my1993"
}


###
GET {{baseUrl}}/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiTS55b29uZ2kiLCJlbWFpbCI6Im1pbi55dW5nZ2lAZXhhbXBsZS5jb20iLCJpbWFnZSI6bnVsbCwiaWF0IjoxNzA3NTk4OTA1LCJleHAiOjE3MDc2MDI1MDV9.2Gta_ba0g3VvRE6fcZHrkcPlRT7YbjiS38HD0YCjjz4
###
GET {{baseUrl}}/auth/profile
Content-Type: application/json
Authorization: Bearer

###
GET {{baseUrl}}/bothUsers
Content-Type: application/json
Authorization: Bearer

###
GET {{baseUrl}}/only-users
Content-Type: application/json
Authorization: Bearer

###
GET {{baseUrl}}/only-admin
Content-Type: application/json
Authorization: Bearer
